### ISSUE TITLE
host path

### ISSUE THREAD

**Issue by jharpster** [ianturton/geoserver-vagrant#2]
Looks like an issue with missing path?
<img width="650" alt="screen shot 2016-03-17 at 3 41 02 pm" src="https://cloud.githubusercontent.com/assets/224853/13863403/be433eb8-ec56-11e5-9f43-b36707eb4a17.png">

**Comment by ianturton** [comment]
Vagrant is expecting to find your geoserver data directory in the same directory as the Vagrant file. I'll add a note to the README
